In [1]:
import pandas as pd

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [3]:
train.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
train = train.copy()
train = train.drop(columns=['PassengerId', 'Name', 'Cabin','Ticket'])

In [5]:
train.head(5)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [6]:
train['family_count'] = train['SibSp']+train['Parch'] # +1 의미만보면 동승자를 세는 수에 가깝기 때문에 1을 더해주는거 추천
train = train.drop(columns=['SibSp','Parch'])

In [7]:
train.head(10)

   Survived  Pclass     Sex   Age     Fare Embarked  family_count
0         0       3    male  22.0   7.2500        S             1
1         1       1  female  38.0  71.2833        C             1
2         1       3  female  26.0   7.9250        S             0
3         1       1  female  35.0  53.1000        S             1
4         0       3    male  35.0   8.0500        S             0
5         0       3    male   NaN   8.4583        Q             0
6         0       1    male  54.0  51.8625        S             0
7         0       3    male   2.0  21.0750        S             4
8         1       3  female  27.0  11.1333        S             2
9         1       2  female  14.0  30.0708        C             1

In [8]:
train['Embarked'] = train['Embarked'].fillna(train['Embarked'].mode()[0])

train = pd.get_dummies(train, columns=['Embarked'])

In [9]:
train[['Embarked_C','Embarked_Q','Embarked_S']] = \
    train[['Embarked_C','Embarked_Q','Embarked_S']].astype(int)

In [10]:
'''
train['AgeGroup'] = 'adult'                 순서교정요망

train.loc[(train['Age'] < 20) & (train['Sex'] == 'male'), 'AgeGroup'] = 'boy'
train.loc[(train['Age'] < 20) & (train['Sex'] == 'female'), 'AgeGroup'] = 'girl'
train['Age'] = train['Age'].fillna(train['Age'].mean())
'''

"\ntrain['AgeGroup'] = 'adult'                 순서교정요망\n\ntrain.loc[(train['Age'] < 20) & (train['Sex'] == 'male'), 'AgeGroup'] = 'boy'\ntrain.loc[(train['Age'] < 20) & (train['Sex'] == 'female'), 'AgeGroup'] = 'girl'\ntrain['Age'] = train['Age'].fillna(train['Age'].mean())\n"

In [11]:
train['Age'] = train['Age'].fillna(train['Age'].mean())

train['AgeGroup'] = 'adult' 
train.loc[(train['Age'] < 20) & (train['Sex'] == 'male'), 'AgeGroup'] = 'boy'
train.loc[(train['Age'] < 20) & (train['Sex'] == 'female'), 'AgeGroup'] = 'girl'

In [12]:
train.head(10)

,Survived,Pclass,Sex,Age,Fare,family_count,Embarked_C,Embarked_Q,Embarked_S,AgeGroup
0,0,3,male,22.000000,7.2500,1,0,0,1,adult
1,1,1,female,38.000000,71.2833,1,1,0,0,adult
2,1,3,female,26.000000,7.9250,0,0,0,1,adult
3,1,1,female,35.000000,53.1000,1,0,0,1,adult
4,0,3,male,35.000000,8.0500,0,0,0,1,adult
5,0,3,male,29.699118,8.4583,0,0,1,0,adult
6,0,1,male,54.000000,51.8625,0,0,0,1,adult
7,0,3,male,2.000000,21.0750,4,0,0,1,boy
8,1,3,female,27.000000,11.1333,2,0,0,1,adult
9,1,2,female,14.000000,30.0708,1,1,0,0,girl

In [13]:
train['Sex'] = train['Sex'].map({'male':0, 'female':1})
train = pd.get_dummies(train,columns=['AgeGroup'],drop_first=True)

In [14]:
train.head(5)

,Survived,Pclass,Sex,Age,Fare,family_count,Embarked_C,Embarked_Q,Embarked_S,AgeGroup_boy,AgeGroup_girl
0,0,3,0,22.0,7.2500,1,0,0,1,False,False
1,1,1,1,38.0,71.2833,1,1,0,0,False,False
2,1,3,1,26.0,7.9250,0,0,0,1,False,False
3,1,1,1,35.0,53.1000,1,0,0,1,False,False
4,0,3,0,35.0,8.0500,0,0,0,1,False,False

In [15]:
train[['AgeGroup_boy','AgeGroup_girl']] = \
    train[['AgeGroup_boy','AgeGroup_girl']].astype(int)

In [16]:
train.head(5)

,Survived,Pclass,Sex,Age,Fare,family_count,Embarked_C,Embarked_Q,Embarked_S,AgeGroup_boy,AgeGroup_girl
0,0,3,0,22.0,7.2500,1,0,0,1,0,0
1,1,1,1,38.0,71.2833,1,1,0,0,0,0
2,1,3,1,26.0,7.9250,0,0,0,1,0,0
3,1,1,1,35.0,53.1000,1,0,0,1,0,0
4,0,3,0,35.0,8.0500,0,0,0,1,0,0

In [17]:
X = train.drop('Survived',axis=1)
y = train['Survived']

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [30]:
model = LogisticRegression(max_iter=1000)        # (max_iter=1000) 넣어주는거 추천
model.fit(X_train,y_train)
pred = model.predict(X_val)

In [31]:
from sklearn.metrics import accuracy_score

accuracy_score(y_val, pred)

0.8044692737430168

In [22]:
test = test.copy()
test = test.drop(columns=['PassengerId', 'Name', 'Cabin','Ticket'])

test['family_count'] = test['SibSp']+test['Parch']
test = test.drop(columns=['SibSp','Parch'])

test['Embarked'] = test['Embarked'].fillna(test['Embarked'].mode()[0])
test = pd.get_dummies(test, columns=['Embarked'])
test[['Embarked_C','Embarked_Q','Embarked_S']] = \
    test[['Embarked_C','Embarked_Q','Embarked_S']].astype(int)

test['Age'] = test['Age'].fillna(test['Age'].mean())

test['AgeGroup'] = 'adult' 
test.loc[(test['Age'] < 20) & (test['Sex'] == 'male'), 'AgeGroup'] = 'boy'
test.loc[(test['Age'] < 20) & (test['Sex'] == 'female'), 'AgeGroup'] = 'girl'
test['Sex'] = test['Sex'].map({'male':0, 'female':1})
test = pd.get_dummies(test,columns=['AgeGroup'],drop_first=True)
test[['AgeGroup_boy','AgeGroup_girl']] = \
    test[['AgeGroup_boy','AgeGroup_girl']].astype(int)

In [23]:
X = train.drop('Survived', axis=1)
y = train['Survived']

X, test = X.align(test, axis=1, fill_value=0)

In [24]:
test.head()

,Pclass,Sex,Age,Fare,family_count,Embarked_C,Embarked_Q,Embarked_S,AgeGroup_boy,AgeGroup_girl
0,3,0,34.5,7.8292,0,0,1,0,0,0
1,3,1,47.0,7.0000,1,0,0,1,0,0
2,2,0,62.0,9.6875,0,0,1,0,0,0
3,3,0,27.0,8.6625,0,0,0,1,0,0
4,3,1,22.0,12.2875,2,0,0,1,0,0

In [25]:
test['Fare'] = test['Fare'].fillna(test['Fare'].mean())

In [26]:
model.fit(X, y)

test_pred = model.predict(test)

c:\Users\mosej\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [27]:
model.fit(X, y)

test_pred = model.predict(test)

c:\Users\mosej\AppData\Local\Python\pythoncore-3.12-64\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [29]:
test_raw = pd.read_csv('test.csv')

submission = pd.DataFrame({
    'PassengerId': test_raw['PassengerId'],
    'Survived': test_pred
})

submission.to_csv('submission.csv', index=False)

submission.head()

   PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1